clear A                C2t_22           Ecoord_y_p       etpl_face_block  invJx_p          ny_i       ...         
Ai               C2t_22n          Jwp              etpl_iface       invJy_n          pen        ...      
Aj               D2t_11           Jx_n             fn               invJy_p          sNr        ...   
B                D2t_11n          Jx_p             glov_nn          j                sNr_n      ...
Bi               D2t_12           Jy_n             gp               j2               sNr_p      ...
Bj               D2t_12n          Jy_p             gwi              nD               sdNr       ...
Block_n          D2t_21           K_eig_all        half             nelblo_all_i     si         ...
C                D2t_21n          block_index_i    i                nen              swp        ...
C2t_11           D2t_22           dNx_n            i2               ngp              v          ...
C2t_11n          D2t_22n          dNx_p            index_n          no_blocks_i      vdNr       ...
C2t_12           E                dNy_n            index_p          nsgp             vwp        ...
C2t_12n          Ecoord_x_n       dNy_p            indx_dNr         num_blocks       weighti    ...
C2t_21           Ecoord_x_p       det              indx_sNr         num_faces                   ...
C2t_21n          Ecoord_y_n       etpl_face        invJx_n          nx_i                        ...